#!/usr/local/bin/node
var exec = require('child_process').exec;
var child;
command = "ps -e -o pid"
var ps;
child = exec(command,
   function (error, stdout, stderr) {
      output(stdout);
});

var regex = /([0-9])\w+/

function output(str){
    var lines = str.split(/\r?\n/);
    lines.shift();
    console.log(Math.max.apply(null, lines));
}